- name: Create new service and scale application
  hosts: localhost
  user: ubuntu

  tasks:
  - name: kubect service
    shell:
      cmd: kubectl expose deployment/kubernetes-server --type="NodePort" --port 8080 --name kubernetes-server

  - name: kubect scale
    shell:
      cmd: kubectl scale deployments/kubernetes-server --replicas=4
